services:
  # Development services
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: wealthin
      POSTGRES_PASSWORD: "0astKckFzwDRgV7JR8g-EJKux49p7Fu6"
    volumes:
      - wealthin_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    ports:
      - "8091:6379"
    command: redis-server --requirepass "dc9jDSISqiHcRvu9BDuzvIpRqgMi8tVD"
    environment:
      - REDIS_REPLICATION_MODE=master

  # Test services
  postgres_test:
    image: pgvector/pgvector:pg16
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: wealthin_test
      POSTGRES_PASSWORD: "V8lDBSZ6ArgBCaLBI2b62U9oqlqqcGYN"
    volumes:
      - wealthin_test_data:/var/lib/postgresql/data

  redis_test:
    image: redis:6.2.6
    ports:
      - "9091:6379"
    command: redis-server --requirepass "qZpCfLWpOyWGgtMVZ5aKucde4HssXpzw"
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  wealthin_data:
  wealthin_test_data:
